version: '3.1'

services:

  db:
    image: postgres:13.12
    restart: always    #автоматический повторный запуск для контейнера преджевременно завершившего работу
    container_name: testcourse
    ports:
      - 7723:5432 #система / контейнер
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testcourse